#!/bin/sh

if ! head -1 "$1" | grep -qE "^(feat|fix|perf|refactor|style|test|build|ops|docs|chore)(\(.+?\))?: .{1,}$"; then
    echo "Invalid commit message. Must start with one of feat|fix|perf|refactor|style|test|build|ops|docs|chore" >&2
    exit 1
fi

if ! head -1 "$1" | grep -qE "^.{1,72}$"; then
    echo "Aborting commit. Your commit message is too long." >&2
    exit 1
fi